frase='Eu amo meu cachorro, Sam'
print(frase[11:])
print(frase[11:19])
print(frase[:2])
print(frase[:6])
print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,16))
print(frase.find('deo'))
print(frase.find('orro'))
print('Curso'in frase)
print('Sam' in frase)
print(frase.title())
print(frase.upper())
print(frase.lower())
print(frase.split())
print(frase.replace('cachorro','bebê'))
print(len(frase.split()))
dividido=frase.split()
print(dividido[0])
print(dividido[2])